name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test_bun:
    name: Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run test
        env:
          CI: true
